// Auto-generated comprehensive AWS CLI data
// Generated by generate-aws-data.py

import { Service } from './aws-commands';

const GLOBAL_PARAMS = [
  { name: "--debug", description: "Turn on debug logging" },
  { name: "--endpoint-url <value>", description: "Override command's default URL" },
  { name: "--no-verify-ssl", description: "Disable SSL certificate verification" },
  { name: "--output <value>", description: "Output format (json|text|table|yaml)" },
  { name: "--query <value>", description: "JMESPath query string" },
  { name: "--profile <value>", description: "Use a specific profile" },
  { name: "--region <value>", description: "AWS region to use" }
];

export const comprehensiveServices: Service[] = [
];