#!/usr/bin/env python3
"""
Generate comprehensive AWS CLI command data for the search application.
This script queries AWS CLI help to extract services, commands, and parameters.
"""

import subprocess
import json
import re

# List of AWS services to include (from user's request)
SERVICES = [
    # Core Identity & Access
    "iam", "sts", "kms", "secretsmanager", "cognito-idp", "organizations", "sso", "cloudformation",
    # Compute & Containers  
    "ec2", "lambda", "lightsail", "ecs", "eks", "elasticbeanstalk", "ecr",
    # Storage & Data
    "s3", "ebs", "efs", "dynamodb", "glacier", "athena", "sagemaker",
    # Networking
    "ec2", "apigateway", "cloudfront", "elbv2", "ec2",  # VPC is part of ec2
    # Databases
    "rds", "redshift", "docdb",
    # Messaging
    "sqs", "sns", "mq",
    # Management & Security
    "cloudtrail", "guardduty", "ssm", "cloudwatch", "events", "wafv2", 
    "fms", "inspector", "securityhub", "shield", "config", "detective", "support",
    # Other
    "datapipeline", "codepipeline", "codecommit", "workdocs", "glue", 
    "emr", "apprunner", "acm", "gamelift"
]

def get_service_commands(service):
    """Get list of commands for a service"""
    try:
        result = subprocess.run(
            ['aws', service, 'help'],
            capture_output=True,
            text=True,
            timeout=5
        )
        
        # Parse help output to extract commands
        commands = []
        in_commands_section = False
        
        for line in result.stdout.split('\n'):
            if 'AVAILABLE COMMANDS' in line or 'COMMANDS' in line:
                in_commands_section = True
                continue
            
            if in_commands_section:
                # Commands are typically indented with 'o' or '*'
                match = re.match(r'\s+[o\*]\s+(\S+)', line)
                if match:
                    cmd = match.group(1)
                    if cmd not in ['help', 'wait']:
                        commands.append(cmd)
                        
                # Stop at next section
                if line.strip() and not line.startswith(' '):
                    break
                    
        return commands[:10]  # Limit to top 10 commands per service
    except Exception as e:
        print(f"Error getting commands for {service}: {e}")
        return []

def generate_typescript_data():
    """Generate TypeScript data structure"""
    
    output = []
    output.append("// Auto-generated comprehensive AWS CLI data")
    output.append("// Generated by generate-aws-data.py")
    output.append("")
    output.append("import { Service } from './aws-commands';")
    output.append("")
    output.append("const GLOBAL_PARAMS = [")
    output.append('  { name: "--debug", description: "Turn on debug logging" },')
    output.append('  { name: "--endpoint-url <value>", description: "Override command\'s default URL" },')
    output.append('  { name: "--no-verify-ssl", description: "Disable SSL certificate verification" },')
    output.append('  { name: "--output <value>", description: "Output format (json|text|table|yaml)" },')
    output.append('  { name: "--query <value>", description: "JMESPath query string" },')
    output.append('  { name: "--profile <value>", description: "Use a specific profile" },')
    output.append('  { name: "--region <value>", description: "AWS region to use" }')
    output.append("];")
    output.append("")
    output.append("export const comprehensiveServices: Service[] = [")
    
    for service in set(SERVICES):  # Remove duplicates
        print(f"Processing {service}...")
        commands = get_service_commands(service)
        
        if not commands:
            continue
            
        output.append("  {")
        output.append(f'    name: "{service}",')
        output.append(f'    description: "AWS {service.upper()}",')
        output.append("    commands: [")
        
        for cmd in commands:
            output.append("      {")
            output.append(f'        name: "{cmd}",')
            output.append(f'        description: "{cmd.replace("-", " ").title()}",')
            output.append("        parameters: [...GLOBAL_PARAMS]")
            output.append("      },")
        
        output.append("    ]")
        output.append("  },")
    
    output.append("];")
    
    return '\n'.join(output)

if __name__ == "__main__":
    print("Generating comprehensive AWS CLI data...")
    data = generate_typescript_data()
    
    with open('lib/aws-services-generated.ts', 'w') as f:
        f.write(data)
    
    print("Generated lib/aws-services-generated.ts")
